### ISSUE TITLE
atoi.cl does not respond 

### ISSUE THREAD

**Issue by realamirhe** [mtp1376/compiler-project#1]
`ERROR`: 0: Type-Check: class Main not found

**Comment by mtp1376** [comment]
Hello and thank you for your attention.
The file `atoi.cl` is not supposed to get run individually, but it should be used as a library.
So you may use a command like this to run the project:
`coolc assignment1.cl atoi.cl` for compilation and `spim assignment1.s` to run it.

**Comment by mtp1376** [comment]
@amirHossein-Ebrahimi

**Comment by realamirhe** [comment]
thank you there was problem with cool interpreter.
It can not combine files
